// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.js",
  },
  datasource: {
<<<<<<< HEAD
    url: process.env.DATABASE_URL!,
=======
    url: env("DATABASE_URL"),
>>>>>>> aee8a1156530dd97bb8998cf463bbb41024edf46
  },
});
