name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 깃허브 액션 서버에서 빌드가 잘 되는지 미리 체크
      - name: Setup Node.js
        uses: aws-actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Check
        run: |
          npm ci
          npx prisma generate
          npm run build

      # 실제 EC2 서버에 접속해서 배포 명령어 실행
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IP
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }} # .pem 키 파일 내용
          script: |
            cd ~/7-sprint-mission/sprint11 
            git pull origin main
            npm install
            npx prisma generate
            npx prisma migrate deploy
            npm run build

            # PM2로 서버 재시작
            # 프로젝트이름은 pm2 list에 뜨는 이름으로 수정하세요.
            pm2 reload all || pm2 start dist/main.js --name "my-app"

            echo "배포가 완료되었습니다!"
